version: 0.2

phases:
  pre_build:
    commands:
      - echo CODECOMMIT_REPOSITORY_NAME $CODECOMMIT_REPOSITORY_NAME
      - echo CODECOMMIT_PULL_REQUEST_ID $CODECOMMIT_PULL_REQUEST_ID
      - echo CODECOMMIT_SOURCE_COMMIT_ID $CODECOMMIT_SOURCE_COMMIT_ID
      - echo CODECOMMIT_DESTINATION_COMMIT_ID $CODECOMMIT_DESTINATION_COMMIT_ID
      - echo IS_TEST_FAILURE $IS_TEST_FAILURE
  build:
    commands:
      - |
        if [ -z "$IS_TEST_FAILURE" ]; then
          echo $CODEBUILD_BUILD_ID > artifact
        else
          exit 1
        fi
artifacts:
  files:
    - artifact
  discard-paths: yes
