version: 0.2

phases:
  pre_build:
    commands:
      - echo REPOSITORY_NAME $REPOSITORY_NAME
      - echo PULL_REQUEST_ID $PULL_REQUEST_ID
      - echo BEFORE_COMMIT_ID $BEFORE_COMMIT_ID
      - echo AFTER_COMMIT_ID $AFTER_COMMIT_ID
  build:
    commands:
      - perl example/build.pl > artifact
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          STATUS=SUCCESS; export SUCCESS;
        else
          STATUS=FAILURE; export FAILURE;
        fi
      - aws codecommit post-comment-for-pull-request --repository-name $REPOSITORY_NAME --pull-request-id $PULL_REQUEST_ID --before-commit-id $BEFORE_COMMIT_ID --after-commit-id $AFTER_COMMIT_ID --content "CodeBuild has completed. Your branch is in a state of $STATUS"
artifacts:
  files:
    - artifact
  discard-paths: yes
