version: 0.2

phases:
  pre_build:
    commands:
      - echo CODECOMMIT_REPOSITORY_NAME $CODECOMMIT_REPOSITORY_NAME
      - echo CODECOMMIT_PULL_REQUEST_ID $CODECOMMIT_PULL_REQUEST_ID
      - echo CODECOMMIT_SOURCE_COMMIT_ID $CODECOMMIT_SOURCE_COMMIT_ID
      - echo CODECOMMIT_DESTINATION_COMMIT_ID $CODECOMMIT_DESTINATION_COMMIT_ID
  build:
    commands:
      - perl example/build.pl > artifact
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          BUILD_STATUS_MESSAGE="Your branch completed successfully";
        else
          BUILD_STATUS_MESSAGE="Your branch failed. View the CodeBuild job for details. You must resolve before the branch can be merged.";
        fi
      - aws codecommit post-comment-for-pull-request --repository-name $CODECOMMIT_REPOSITORY_NAME --pull-request-id $CODECOMMIT_PULL_REQUEST_ID --before-commit-id $CODECOMMIT_SOURCE_COMMIT_ID --after-commit-id $CODECOMMIT_DESTINATION_COMMIT_ID --content "CodeBuild has completed. $BUILD_STATUS_MESSAGE"
artifacts:
  files:
    - artifact
  discard-paths: yes
