#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

aws cloudformation update-stack \
      --stack-name $CLOUDFORMATION_STACK_NAME \
      --parameters ParameterKey=CodeCommitRepositoryName,ParameterValue=$CODECOMMIT_REPOSITORY_NAME \
                   ParameterKey=CodeBuildProjectName,ParameterValue=$CODEBUILD_PROJECT_NAME \
      --template-body file://$DIR/stack.yaml \
      --capabilities CAPABILITY_IAM \
      --capabilities CAPABILITY_NAMED_IAM && \

      aws cloudformation wait stack-update-complete \
        --stack-name $CLOUDFORMATION_STACK_NAME
